# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 2bebetter
email: tbebetter@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  to be a better man
keyword: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://2bebetter.github.io"           # your host, for absolute URL

#Social settings
weibo_id: 5731069177
weibo_username: 盼西楼雅集
github_username:  2bebetter
highlighter-theme: monokai
category_dir: category/
tag_dir: tag/

# Build settings
highlighter-theme: monokai

date_format: "%Y-%M-%D"
highlighter: rouge
permalink: pretty
paginate: 10
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

markdown: kramdown
kramdown:
  input:                     GFM
  auto_ids:                  true
  footnote_nr:               1
  entity_output:             as_char
  toc_levels:                1..6
  smart_quotes:              lsquo,rsquo,ldquo,rdquo
  enable_coderay:            false
  hard_wrap:                 false
  transliterated_header_ids: true
  footnote_backlink:         "&#8617;&#xfe0e;"


category_dir: category/
tag_dir: tag/